# -*- mode: dockerfile -*-
FROM node:12.4.0-alpine
ARG VUE_APP_WEB_BACKEND_URL
ARG VUE_APP_GTAG_ID
RUN apk add --no-cache git make ncurses gawk
WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN npm install
# RUN npm install @vue/cli@3.11.0 -g
ENV VUE_APP_WEB_BACKEND_URL=${VUE_APP_WEB_BACKEND_URL}
ENV VUE_APP_DEBUG=true
ENV VUE_APP_GTAG_ID=${VUE_APP_GTAG_ID}
ENV PATH /app/node_modules/.bin:$PATH
CMD ["npm", "run", "serve"]
