version: "3.4"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WEB_CONCURRENCY=2
    volumes:
      - ./logs/web_backend:/tmp/epigraphdb_web/logs
    ports:
      - ${DOCKER_BACKEND_PORT:-8010}:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_WEB_BACKEND_URL=${FRONTEND_BACKEND_URL:-localhost:8010}
        - VUE_APP_GTAG_ID=${FRONTEND_GTAG_ID}
    restart: unless-stopped
    ports:
      - ${DOCKER_FRONTEND_PORT:-8011}:80

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        VUE_APP_WEB_BACKEND_URL: ${FRONTEND_BACKEND_URL:-localhost:8010}
    restart: unless-stopped
    ports:
      - ${DOCKER_DASHBOARD_PORT:-8012}:80

  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    command: mongod --auth
    volumes:
      - mongo_data:/data/db
    ports:
      - ${DOCKER_MONGO_PORT:-6570}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: epigraphdb
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
      MONGO_INITDB_DATABASE: epigraphdb_mongo
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    restart: unless-stopped
    ports:
      - ${DOCKER_ES_PORT:-6550}:9200
    tty: true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/backup

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    restart: unless-stopped
    ports:
      - ${DOCKER_KIBANA_PORT:-6555}:5601
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
