# -*- mode: dockerfile -*-
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

RUN curl -fsSL https://deb.nodesource.com/setup_15.x | bash
RUN apt-get --allow-releaseinfo-change update \
  && apt-get install -y nodejs
RUN python -m pip install --upgrade pip

COPY ./poetry.lock ./pyproject.toml ./
# poetry and its dependencies
  # TODO: why poetry fails to install its dependencies??
RUN pip install poetry appdirs
RUN poetry config virtualenvs.create false \
  && poetry install

COPY ./ /app
